services:
  - type: web
    name: access-request-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: WEBHOOK_SECRET
        value: f3a225c-f1db-430d-8a73-818a9133df92
      - key: REQUIRE_SIGNATURE
        value: "True"
      - key: PORT
        value: "8080" 